# Generated by Django 5.1.1 on 2024-11-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="item",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="item",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="date_created",
            new_name="date_posted",
        ),
    ]
