# Generated by Django 5.1.1 on 2024-11-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_name_listing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
