# Generated by Django 5.1.1 on 2024-11-06 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_category_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("electronics", "electronics"),
                    ("fashion", "fashion"),
                    ("home", "home"),
                    ("toys", "toys"),
                    ("other", "other"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
