# Generated by Django 5.1.1 on 2024-12-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listing_category_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Electronics", "electronics"),
                    ("Fashion", "fashion"),
                    ("Home", "home"),
                    ("Toys", "toys"),
                    ("Other", "other"),
                ],
                max_length=64,
            ),
        ),
    ]
