# Generated by Django 5.1.1 on 2024-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_listing_watchers_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
