# Generated by Django 5.1.1 on 2024-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_listing_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5
            ),
        ),
    ]
