# Generated by Django 5.1.1 on 2024-12-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_listing_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
