# Generated by Django 5.1.1 on 2024-12-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_listing_current_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="current_price",
            new_name="current_bid",
        ),
    ]
