# Generated by Django 5.1.1 on 2024-12-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_rename_current_price_listing_current_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_bid",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
