# Generated by Django 5.1.1 on 2024-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_alter_listing_highest_bidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watch_count",
            field=models.IntegerField(default=0),
        ),
    ]
